# Generated by Django 4.1.1 on 2023-01-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="invoiceitem", name="qty"),
        migrations.AddField(model_name="invoiceitem", name="fees", field=models.CharField(blank=True, max_length=100, null=True)),
    ]
