# Generated by Django 4.1.1 on 2022-10-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("invoices", "0001_initial")]

    operations = [migrations.RemoveField(model_name="invoiceitem", name="customer")]
