# Generated by Django 4.1.1 on 2022-11-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="invoiceitem", name="sub_total", field=models.PositiveIntegerField(blank=True, default=1, editable=False, verbose_name="Sub Total"), preserve_default=False
        )
    ]
