# Generated by Django 4.1.1 on 2022-10-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("invoices", "0002_remove_invoiceitem_customer")]

    operations = [migrations.AlterField(model_name="invoice", name="customer", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="invoices.customer"))]
