# Generated by Django 4.1.1 on 2022-11-08 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_brandingimage'),
        ('invoices', '0003_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='services_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_items', to='services.services'),
        ),
    ]
