# Generated by Django 4.1.1 on 2022-11-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone_no',
        ),
    ]
