# Generated by Django 4.1.1 on 2022-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notification", "0001_initial")]

    operations = [migrations.AddField(model_name="broadcastnotification", name="link", field=models.URLField(blank=True, null=True))]
