# Generated by Django 4.1.1 on 2022-11-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcastnotification',
            old_name='send',
            new_name='sent',
        ),
    ]
