<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-12-01 08:53
=======
# Generated by Django 4.1.1 on 2022-12-01 08:51
>>>>>>> 752e208dc6c2ff0b16b96671b588729297e2ea46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="services", name="time_for_service"),
        migrations.AlterField(model_name="services", name="actual_service_charge", field=models.CharField(max_length=100)),
        migrations.AlterField(model_name="services", name="service_charge", field=models.CharField(max_length=100)),
        migrations.AlterField(model_name="services", name="upload_form", field=models.URLField()),
    ]
