# Generated by Django 4.1.1 on 2022-11-18 11:13

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("services", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="brandingimage", name="image", field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="service/", verbose_name="Image")
        )
    ]
