# Generated by Django 4.1.1 on 2022-11-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0001_initial")]

    operations = [migrations.RemoveField(model_name="brandingimage", name="ppoi")]
