# Generated by Django 4.1.1 on 2022-12-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0001_initial")]

    operations = [migrations.AddField(model_name="brandingimage", name="is_verified", field=models.BooleanField(default=False, verbose_name="Mark as Verified"))]
