# Generated by Django 4.1.1 on 2022-12-05 06:52

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("services", "0001_initial")]

    operations = [migrations.AlterField(model_name="brandingimage", name="image", field=versatileimagefield.fields.VersatileImageField(upload_to="service/", verbose_name="Image"))]
