# Generated by Django 4.1.1 on 2022-12-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0002_alter_brandingimage_image"), ("services", "0002_brandingimage_is_verified")]

    operations = []
