# Generated by Django 4.1.1 on 2022-10-19 09:57

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(default='deafult-01.jpg', null=True, upload_to='Profile'),
        ),
    ]
