# Generated by Django 4.1.1 on 2022-11-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0001_initial")]

    operations = [
        migrations.AddField(model_name="commonservicesposter", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="festivelposter", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="importantposter", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="newserviceposter", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="professionalposter", name="detail_link", field=models.URLField(default=1), preserve_default=False),
    ]
