# Generated by Django 4.1.1 on 2022-12-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="order", name="is_active"),
        migrations.RemoveField(model_name="order", name="valid_from"),
        migrations.RemoveField(model_name="order", name="valid_upto"),
        migrations.RemoveField(model_name="subscription", name="is_active"),
        migrations.AddField(model_name="order", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Success", "Success"), ("Failure", "Failure"), ("Pending", "Pending")], default="Pending", max_length=254, verbose_name="Payment Status"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("Success", "Success"), ("Failure", "Failure"), ("Pending", "Pending")], default="Pending", max_length=254, verbose_name="Payment Status"
            ),
        ),
    ]
