# Generated by Django 4.1.1 on 2022-12-03 10:10

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("web", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="OnloadPopup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="Onload_Popup/", verbose_name="Image")),
                ("ppoi", versatileimagefield.fields.PPOIField(default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI")),
            ],
            options={"verbose_name_plural": "Onload Popup"},
        )
    ]
