# Generated by Django 4.1.1 on 2022-11-18 06:07

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("web", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("days", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("is_active", models.BooleanField(default=False, verbose_name="Mark as Active")),
            ],
            options={"verbose_name": "Upgrade Plan", "verbose_name_plural": "Upgrade Plans"},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valid_from", models.DateTimeField()),
                ("valid_upto", models.DateTimeField(blank=True, editable=False)),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="upgrade_plan", to="web.plan")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="upgraded_user", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "User Subscription", "verbose_name_plural": "User Subscriptions"},
        ),
    ]
