# Generated by Django 4.1.1 on 2022-12-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0002_onloadpopup")]

    operations = [migrations.AddField(model_name="downloaddocuments", name="title", field=models.CharField(default=1, max_length=100), preserve_default=False)]
