# Generated by Django 4.1.1 on 2022-12-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0002_remove_order_is_active_remove_order_valid_from_and_more")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="types",
            field=models.CharField(choices=[("Access", "Access"), ("Subscription", "Subscription")], default=1, max_length=254, verbose_name="Type"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="types",
            field=models.CharField(blank=True, choices=[("Access", "Access"), ("Subscription", "Subscription")], max_length=254, null=True, verbose_name="Type"),
        ),
    ]
