# Generated by Django 4.1.1 on 2023-01-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0002_addonservices_order_types")]

    operations = [migrations.AlterField(model_name="subscription", name="valid_upto", field=models.DateTimeField(blank=True))]
