# Generated by Django 4.1.1 on 2022-11-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0002_commonservicesposter_detail_link_and_more")]

    operations = [
        migrations.AddField(model_name="downloaddocuments", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="downloadforms", name="detail_link", field=models.URLField(default=1), preserve_default=False),
    ]
