# Generated by Django 4.1.1 on 2022-10-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userregistration_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
