# Generated by Django 4.1.1 on 2022-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0003_downloaddocuments_title")]

    operations = [
        migrations.AlterModelOptions(name="otherideas", options={"verbose_name_plural": "Add to the Business"}),
        migrations.AlterField(model_name="order", name="valid_upto", field=models.DateTimeField(blank=True, editable=False, null=True)),
    ]
