# Generated by Django 4.1.1 on 2022-11-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0003_downloaddocuments_detail_link_and_more")]

    operations = [
        migrations.AddField(model_name="agencyportal", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="agentbonus", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="backofficeservices", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="marketingtips", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="otherideas", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="softwares", name="detail_link", field=models.URLField(default=1), preserve_default=False),
        migrations.AddField(model_name="tools", name="detail_link", field=models.URLField(default=1), preserve_default=False),
    ]
