<<<<<<< HEAD
# Generated by Django 4.1.1 on 2023-01-05 04:38
=======
# Generated by Django 4.1.1 on 2023-01-05 04:31
>>>>>>> 2f24a658804d51c30bead773a8b43b46ac1a8534

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0003_alter_subscription_valid_upto")]

    operations = [
        migrations.AlterField(model_name="order", name="types", field=models.CharField(choices=[("Access", "Access")], max_length=254, verbose_name="Type")),
        migrations.AlterField(
            model_name="subscription", name="types", field=models.CharField(blank=True, choices=[("Access", "Access")], max_length=254, null=True, verbose_name="Type")
        ),
    ]
