# Generated by Django 4.1.1 on 2022-11-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("web", "0004_subscription_amount")]

    operations = [migrations.RemoveField(model_name="subscription", name="days")]
