# Generated by Django 4.1.1 on 2023-01-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0004_alter_order_types_alter_subscription_types")]

    operations = [
        migrations.AlterField(
            model_name="subscription", name="types", field=models.CharField(choices=[("Access", "Access")], default="Access", max_length=254, verbose_name="Subscription Type")
        )
    ]
