# Generated by Django 4.1.1 on 2022-12-01 08:51

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("web", "0004_agencyportal_detail_link_agentbonus_detail_link_and_more")]

    operations = [
        migrations.CreateModel(
            name="AddonServices",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="Agent_Bonus/", verbose_name="Image")),
                ("ppoi", versatileimagefield.fields.PPOIField(default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI")),
                ("link", models.URLField()),
                ("detail_link", models.URLField()),
            ],
            options={"verbose_name_plural": "Add-on Services"},
        ),
        migrations.DeleteModel(name="CertificateImages"),
    ]
