# Generated by Django 4.1.1 on 2022-10-21 05:19

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_userregistration_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='Profile'),
        ),
    ]
