# Generated by Django 4.1.1 on 2022-11-21 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("web", "0006_alter_subscription_valid_from")]

    operations = [migrations.AlterField(model_name="subscription", name="valid_from", field=models.DateTimeField(default=django.utils.timezone.now))]
