# Generated by Django 4.1.1 on 2022-10-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_userregistration_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='profile_image',
        ),
    ]
