# Generated by Django 4.1.1 on 2022-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_commonservicesposter_title_festivelposter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
