# Generated by Django 4.1.1 on 2022-10-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_latestnews_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
