# Generated by Django 4.1.1 on 2022-10-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_latestnews_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='DownloadDocuments',
        ),
        migrations.RenameModel(
            old_name='GenerateForms',
            new_name='DownloadForms',
        ),
        migrations.AlterModelOptions(
            name='downloaddocuments',
            options={'verbose_name_plural': 'Download Documents'},
        ),
        migrations.AlterModelOptions(
            name='downloadforms',
            options={'verbose_name_plural': 'Download Forms'},
        ),
    ]
