# Generated by Django 4.1.1 on 2022-10-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_changepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userregistration'),
        ),
    ]
