# Generated by Django 4.1.1 on 2022-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_changepassword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepassword',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
