# Generated by Django 4.1.1 on 2022-11-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_changepassword_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='district',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='pincode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
