# Generated by Django 4.1.1 on 2022-11-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_userregistration_district_userregistration_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
