# Generated by Django 4.1.1 on 2022-11-05 05:37

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_userregistration_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usk_logo', versatileimagefield.fields.VersatileImageField(default='USK Login Logo.png', null=True, upload_to='USKimages')),
                ('bruvsha_logo', versatileimagefield.fields.VersatileImageField(default='Bruvsha Logo.png', null=True, upload_to='USKimages')),
                ('seal', versatileimagefield.fields.VersatileImageField(default='Seal.png', null=True, upload_to='USKimages')),
                ('sign', versatileimagefield.fields.VersatileImageField(default='Sign.png', null=True, upload_to='USKimages')),
            ],
        ),
    ]
