# Generated by Django 4.1.1 on 2022-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [migrations.AddField(model_name="user", name="created", field=models.DateField(auto_now_add=True, null=True))]
