# Generated by Django 4.1.1 on 2022-11-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=17, verbose_name='Temporary password'),
        ),
    ]
