<<<<<<< HEAD
# Generated by Django 4.1.1 on 2023-01-05 04:38
=======
# Generated by Django 4.1.1 on 2023-01-05 04:31
>>>>>>> 2f24a658804d51c30bead773a8b43b46ac1a8534

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [migrations.AddField(model_name="user", name="referal_code", field=models.CharField(blank=True, max_length=20, null=True))]
