# Generated by Django 4.1.1 on 2022-11-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [migrations.RenameField(model_name="user", old_name="istrict", new_name="district")]
