# Generated by Django 4.1.1 on 2022-11-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_alter_user_temp_password")]

    operations = [migrations.AlterField(model_name="user", name="email", field=models.CharField(max_length=100))]
