# Generated by Django 4.1.1 on 2022-12-22 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_user_created")]

    operations = [
        migrations.RemoveField(model_name="user", name="temp_password"),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex="^\\+?1?\\d{9,15}$")
                ],
                verbose_name="phone number",
            ),
        ),
    ]
