from . import views
from django.urls import path
from django.views.static import serve


app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("expired/", views.expired, name="expired"),
    path("start/", views.start, name="start"),
    path("register/", views.AuthRegistrationView.as_view(), name="register"),
    path("profile/", views.profile, name="profile"),
    path("profile_update/", views.profile_update, name="profile_update"),
    path("settings/", views.settings_menu, name="settings"),
    path("notes/", views.notes, name="notes"),
    path("notification/", views.notification, name="notification"),
    path("generate_poster/", views.generate_poster, name="generate_poster"),
    path("generate_bill/", views.generate_bill, name="generate_bill"),
    path("search_invocie/", views.searching_invoice, name="searching_invoice"),
    path("invoice_search_print/<int:pk>/", views.invoice_search_print, name="invoice_search_print"),
    path("search/", views.search_items, name="search_items"),
    path("generate_form/", views.generate_forms, name="generate_forms"),
    path("download/", serve, {"document_root": "settings.MEDIA_ROOT"}),
    path("documents/", views.documents, name="documents"),
    path("softwares/", views.software, name="software"),
    path("tools/", views.tools, name="tools"),
    path("marketing_tip/", views.marketing_tip, name="marketing_tip"),
    path("other_ideas/", views.other_idea, name="other_idea"),
    path("agency_portal/", views.agency_portal, name="agency_portal"),
    path("back_office_services/", views.back_office_services, name="back_office_services"),
    path("bonus/", views.bonus, name="bonus"),
    path("support/", views.support, name="support"),
    path("support_request/", views.support_request, name="support_request"),
    path("support_ticket/", views.support_ticket, name="support_ticket"),
    path("upgrade_request/", views.upgrade_plan_request, name="upgrade_plan_request"),
    path("FAQ/", views.F_A_Q, name="F_A_Q"),
    path("terms_and_conditions/", views.terms_and_conditions, name="terms_and_conditions"),
    path("call_support/", views.call_support, name="call_support"),
    path("whatsapp_support/", views.whatsapp_support, name="whatsapp_support"),
    path("payment/", views.order_payment, name="order_payment"),
    path("callback/", views.callback, name="callback"),
    path("plan_upgrading/", views.upgrade_plan, name="upgrade_plan"),
    path("upgrade_callback/", views.upgrade_callback, name="upgrade_callback"),
    path("download_pdf_certificate/", views.Certificate.as_view(), name="pdf_certificate"),
    path("buynow_branding_image/", views.buy_now_branding_image, name="buy_now_branding_image"),
    path("add_on_services/", views.add_on_services, name="add_on_services"),
    path("newly_addedd_services/", views.newly_added_services, name="newly_added_services"),
    path("important_poster/", views.important_services, name="important_services"),
]
